// Generated by gencpp from file nao_tutoring_behaviors/ControlMsg.msg
// DO NOT EDIT!


#ifndef NAO_TUTORING_BEHAVIORS_MESSAGE_CONTROLMSG_H
#define NAO_TUTORING_BEHAVIORS_MESSAGE_CONTROLMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_tutoring_behaviors
{
template <class ContainerAllocator>
struct ControlMsg_
{
  typedef ControlMsg_<ContainerAllocator> Type;

  ControlMsg_()
    : nextStep()
    , questionNum(0)
    , questionLevel(0)
    , questionType()
    , robotSpeech()
    , otherInfo()  {
    }
  ControlMsg_(const ContainerAllocator& _alloc)
    : nextStep(_alloc)
    , questionNum(0)
    , questionLevel(0)
    , questionType(_alloc)
    , robotSpeech(_alloc)
    , otherInfo(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nextStep_type;
  _nextStep_type nextStep;

   typedef int64_t _questionNum_type;
  _questionNum_type questionNum;

   typedef int64_t _questionLevel_type;
  _questionLevel_type questionLevel;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _questionType_type;
  _questionType_type questionType;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robotSpeech_type;
  _robotSpeech_type robotSpeech;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _otherInfo_type;
  _otherInfo_type otherInfo;




  typedef boost::shared_ptr< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ControlMsg_

typedef ::nao_tutoring_behaviors::ControlMsg_<std::allocator<void> > ControlMsg;

typedef boost::shared_ptr< ::nao_tutoring_behaviors::ControlMsg > ControlMsgPtr;
typedef boost::shared_ptr< ::nao_tutoring_behaviors::ControlMsg const> ControlMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_tutoring_behaviors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nao_tutoring_behaviors': ['/root/catkin_ws/src/nao_tutoring_behaviors/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "241836c36d056d07e4e04b720ca53a45";
  }

  static const char* value(const ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x241836c36d056d07ULL;
  static const uint64_t static_value2 = 0xe4e04b720ca53a45ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_tutoring_behaviors/ControlMsg";
  }

  static const char* value(const ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nextStep\n\
int64 questionNum\n\
int64 questionLevel\n\
string questionType\n\
string robotSpeech\n\
string otherInfo\n\
";
  }

  static const char* value(const ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nextStep);
      stream.next(m.questionNum);
      stream.next(m.questionLevel);
      stream.next(m.questionType);
      stream.next(m.robotSpeech);
      stream.next(m.otherInfo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_tutoring_behaviors::ControlMsg_<ContainerAllocator>& v)
  {
    s << indent << "nextStep: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.nextStep);
    s << indent << "questionNum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.questionNum);
    s << indent << "questionLevel: ";
    Printer<int64_t>::stream(s, indent + "  ", v.questionLevel);
    s << indent << "questionType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.questionType);
    s << indent << "robotSpeech: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robotSpeech);
    s << indent << "otherInfo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.otherInfo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_TUTORING_BEHAVIORS_MESSAGE_CONTROLMSG_H
